### ISSUE TITLE
Display using headset tracking

### ISSUE THREAD

**Issue by titorgalaxy** [titorgalaxy/Coppelia#1]
CoppeliaDisplayOpenVR:

- [x] Track OpenVR headset
- [x] Transform camera based on headset motion
- [x] Display distinct images in both eyes
